import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Alert,
  Share,
  Dimensions,
} from 'react-native';
import { GeneratedItinerary, MultiDayItinerary, DailyItinerary, BookingInfo } from '../types';

const { width } = Dimensions.get('window');

interface PrintItineraryProps {
  itinerary: GeneratedItinerary | MultiDayItinerary;
  bookingInfo: BookingInfo;
  startingLocation: { address: string };
  returnLocation: { address: string };
  onClose: () => void;
}

const PrintItinerary: React.FC<PrintItineraryProps> = ({
  itinerary,
  bookingInfo,
  startingLocation,
  returnLocation,
  onClose,
}) => {
  const isMultiDay = 'dailyItineraries' in itinerary;

  const formatTime = (timeString: string) => {
    const [hours, minutes] = timeString.split(':');
    const hour = parseInt(hours);
    const ampm = hour >= 12 ? 'PM' : 'AM';
    const formattedHour = hour % 12 || 12;
    return `${formattedHour}:${minutes} ${ampm}`;
  };

  const handlePrint = async () => {
    try {
      const itineraryText = generateItineraryText();
      await Share.share({
        message: itineraryText,
        title: 'My Travel Itinerary',
      });
    } catch (error) {
      Alert.alert('Error', 'Failed to share itinerary');
    }
  };

  const generateItineraryText = () => {
    let text = `🗓️ MY TRAVEL ITINERARY\n\n`;
    text += `📍 Starting Location: ${startingLocation.address}\n`;
    text += `📍 Return Location: ${returnLocation.address}\n\n`;

    if (isMultiDay) {
      const multiDayItinerary = itinerary as MultiDayItinerary;
      text += `📅 Duration: ${multiDayItinerary.totalDays} days\n`;
      text += `📍 Total Places: ${multiDayItinerary.totalPlaces}\n\n`;

      multiDayItinerary.dailyItineraries.forEach((dailyItinerary, index) => {
        text += `DAY ${index + 1} - ${dailyItinerary.date}\n`;
        text += `⏰ ${formatTime(dailyItinerary.startTime)} - ${dailyItinerary.availableHours} hours available\n\n`;
        
        dailyItinerary.schedule.forEach((scheduleItem, scheduleIndex) => {
          text += `${scheduleIndex + 1}. ${scheduleItem.place.name}\n`;
          text += `   📍 ${scheduleItem.place.address}\n`;
          text += `   ⏰ ${formatTime(scheduleItem.arrivalTime)} - ${formatTime(scheduleItem.departureTime)}\n`;
          text += `   ⌛ ${scheduleItem.visitDuration} minutes\n`;
          if (scheduleItem.place.rating) {
            text += `   ⭐ ${scheduleItem.place.rating}/5\n`;
          }
          text += `\n`;
        });
        text += `\n`;
      });
    } else {
      const singleDayItinerary = itinerary as GeneratedItinerary;
      text += `📍 Total Places: ${singleDayItinerary.places.length}\n\n`;
      
      singleDayItinerary.schedule.forEach((scheduleItem, index) => {
        text += `${index + 1}. ${scheduleItem.place.name}\n`;
        text += `   📍 ${scheduleItem.place.address}\n`;
        text += `   ⏰ ${formatTime(scheduleItem.arrivalTime)} - ${formatTime(scheduleItem.departureTime)}\n`;
        text += `   ⌛ ${scheduleItem.visitDuration} minutes\n`;
        if (scheduleItem.place.rating) {
          text += `   ⭐ ${scheduleItem.place.rating}/5\n`;
        }
        text += `\n`;
      });
    }

    if (bookingInfo.ticketBookings.length > 0) {
      text += `🎫 TICKET BOOKINGS:\n\n`;
      bookingInfo.ticketBookings.forEach((ticket, index) => {
        text += `${index + 1}. ${ticket.placeName}\n`;
        text += `   Type: ${ticket.ticketType}\n`;
        text += `   Quantity: ${ticket.quantity}\n`;
        text += `   Price: $${ticket.totalPrice.toFixed(2)}\n\n`;
      });
    }

    if (bookingInfo.rideBookings.length > 0) {
      text += `🚗 RIDE BOOKINGS:\n\n`;
      bookingInfo.rideBookings.forEach((ride, index) => {
        text += `${index + 1}. ${ride.rideType.toUpperCase()}\n`;
        text += `   Route: ${ride.fromLocation} → ${ride.toLocation}\n`;
        text += `   Distance: ${Math.round(ride.distance / 1000 * 10) / 10} km\n`;
        text += `   Duration: ${ride.estimatedDuration} minutes\n`;
        text += `   Price: $${ride.estimatedPrice.toFixed(2)}\n\n`;
      });
    }

    if (bookingInfo.totalCost > 0) {
      text += `💰 TOTAL COST: $${bookingInfo.totalCost.toFixed(2)}\n`;
      text += `   Tickets: $${bookingInfo.totalTicketCost.toFixed(2)}\n`;
      text += `   Rides: $${bookingInfo.totalRideCost.toFixed(2)}\n\n`;
    }

    text += `Generated by NaviNook Travel Planner 🧭`;
    return text;
  };

  const renderDailyItinerary = (dailyItinerary: DailyItinerary, dayIndex: number) => (
    <View key={dayIndex} style={styles.daySection}>
      <Text style={styles.dayTitle}>Day {dayIndex + 1} - {dailyItinerary.date || 'Unknown Date'}</Text>
      <Text style={styles.daySubtitle}>
        {formatTime(dailyItinerary.startTime || '00:00')} • {dailyItinerary.availableHours || 0} hours available
      </Text>
      
      {dailyItinerary.schedule?.map((scheduleItem, index) => (
        <View key={index} style={styles.placeItem}>
          <View style={styles.placeHeader}>
            <Text style={styles.placeNumber}>{index + 1}</Text>
            <View style={styles.placeInfo}>
              <Text style={styles.placeName}>{scheduleItem.place?.name || 'Unknown Place'}</Text>
              <Text style={styles.placeAddress}>{scheduleItem.place?.address || 'No address available'}</Text>
            </View>
          </View>
          <View style={styles.placeDetails}>
            <Text style={styles.placeTime}>
              {formatTime(scheduleItem.arrivalTime || '00:00')} - {formatTime(scheduleItem.departureTime || '00:00')}
            </Text>
            <Text style={styles.placeDuration}>
              {scheduleItem.visitDuration || 0} minutes
            </Text>
            {scheduleItem.place?.rating && (
              <Text style={styles.placeRating}>
                ⭐ {scheduleItem.place.rating}/5
              </Text>
            )}
          </View>
        </View>
      ))}
    </View>
  );

  const renderSingleDayItinerary = () => {
    const singleDayItinerary = itinerary as GeneratedItinerary;
    return (
      <View style={styles.daySection}>
        <Text style={styles.dayTitle}>Your Itinerary</Text>
        <Text style={styles.daySubtitle}>
          {singleDayItinerary.places?.length || 0} places • {Math.round((singleDayItinerary.totalDuration || 0) / 60)} hours
        </Text>
        
        {singleDayItinerary.schedule?.map((scheduleItem, index) => (
          <View key={index} style={styles.placeItem}>
            <View style={styles.placeHeader}>
              <Text style={styles.placeNumber}>{index + 1}</Text>
              <View style={styles.placeInfo}>
                <Text style={styles.placeName}>{scheduleItem.place?.name || 'Unknown Place'}</Text>
                <Text style={styles.placeAddress}>{scheduleItem.place?.address || 'No address available'}</Text>
              </View>
            </View>
            <View style={styles.placeDetails}>
              <Text style={styles.placeTime}>
                {formatTime(scheduleItem.arrivalTime || '00:00')} - {formatTime(scheduleItem.departureTime || '00:00')}
              </Text>
              <Text style={styles.placeDuration}>
                {scheduleItem.visitDuration || 0} minutes
              </Text>
              {scheduleItem.place?.rating && (
                <Text style={styles.placeRating}>
                  ⭐ {scheduleItem.place.rating}/5
                </Text>
              )}
            </View>
          </View>
        ))}
      </View>
    );
  };

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.headerTitle}>📄 Print Itinerary</Text>
        <TouchableOpacity style={styles.closeButton} onPress={onClose}>
          <Text style={styles.closeButtonText}>×</Text>
        </TouchableOpacity>
      </View>

      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        <View style={styles.itineraryHeader}>
          <Text style={styles.itineraryTitle}>🗓️ My Travel Itinerary</Text>
          <View style={styles.locationInfo}>
            <Text style={styles.locationLabel}>Starting Location:</Text>
            <Text style={styles.locationText}>{startingLocation?.address || 'No starting location'}</Text>
          </View>
          <View style={styles.locationInfo}>
            <Text style={styles.locationLabel}>Return Location:</Text>
            <Text style={styles.locationText}>{returnLocation?.address || 'No return location'}</Text>
          </View>
        </View>

        {isMultiDay ? (
          (itinerary as MultiDayItinerary).dailyItineraries.map(renderDailyItinerary)
        ) : (
          renderSingleDayItinerary()
        )}

        {bookingInfo?.ticketBookings?.length > 0 && (
          <View style={styles.bookingSection}>
            <Text style={styles.bookingSectionTitle}>🎫 Ticket Bookings</Text>
            {bookingInfo.ticketBookings.map((ticket, index) => (
              <View key={index} style={styles.bookingItem}>
                <Text style={styles.bookingTitle}>{ticket?.placeName || 'Unknown Place'}</Text>
                <Text style={styles.bookingDetails}>
                  {ticket?.ticketType || 'Unknown Type'} • Qty: {ticket?.quantity || 0} • ${(ticket?.totalPrice || 0).toFixed(2)}
                </Text>
              </View>
            ))}
          </View>
        )}

        {bookingInfo?.rideBookings?.length > 0 && (
          <View style={styles.bookingSection}>
            <Text style={styles.bookingSectionTitle}>🚗 Ride Bookings</Text>
            {bookingInfo.rideBookings.map((ride, index) => (
              <View key={index} style={styles.bookingItem}>
                <Text style={styles.bookingTitle}>{ride?.rideType?.toUpperCase() || 'UNKNOWN'}</Text>
                <Text style={styles.bookingDetails}>
                  {ride?.fromLocation || 'Unknown'} → {ride?.toLocation || 'Unknown'}
                </Text>
                <Text style={styles.bookingDetails}>
                  {Math.round((ride?.distance || 0) / 1000 * 10) / 10} km • {ride?.estimatedDuration || 0} min • ${(ride?.estimatedPrice || 0).toFixed(2)}
                </Text>
              </View>
            ))}
          </View>
        )}

        {bookingInfo?.totalCost > 0 && (
          <View style={styles.totalSection}>
            <Text style={styles.totalTitle}>💰 Total Cost</Text>
            <View style={styles.totalRow}>
              <Text style={styles.totalLabel}>Tickets:</Text>
              <Text style={styles.totalValue}>${(bookingInfo?.totalTicketCost || 0).toFixed(2)}</Text>
            </View>
            <View style={styles.totalRow}>
              <Text style={styles.totalLabel}>Rides:</Text>
              <Text style={styles.totalValue}>${(bookingInfo?.totalRideCost || 0).toFixed(2)}</Text>
            </View>
            <View style={styles.totalDivider} />
            <View style={styles.totalRow}>
              <Text style={styles.totalGrandLabel}>Total:</Text>
              <Text style={styles.totalGrandValue}>${(bookingInfo?.totalCost || 0).toFixed(2)}</Text>
            </View>
          </View>
        )}

        <View style={styles.footer}>
          <Text style={styles.footerText}>Generated by NaviNook Travel Planner 🧭</Text>
        </View>
      </ScrollView>

      <View style={styles.actionButtons}>
        <TouchableOpacity style={styles.printButton} onPress={handlePrint}>
          <Text style={styles.printButtonText}>📤 Share Itinerary</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e1e5f0',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2c3e50',
  },
  closeButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#f8f9fa',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 20,
    color: '#7f8c8d',
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  itineraryHeader: {
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e1e5f0',
    marginBottom: 20,
  },
  itineraryTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#2c3e50',
    textAlign: 'center',
    marginBottom: 16,
  },
  locationInfo: {
    marginBottom: 8,
  },
  locationLabel: {
    fontSize: 14,
    color: '#7f8c8d',
    fontWeight: '600',
  },
  locationText: {
    fontSize: 16,
    color: '#2c3e50',
    marginTop: 2,
  },
  daySection: {
    marginBottom: 24,
  },
  dayTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#2c3e50',
    marginBottom: 4,
  },
  daySubtitle: {
    fontSize: 16,
    color: '#7f8c8d',
    marginBottom: 16,
  },
  placeItem: {
    backgroundColor: '#f8f9ff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e1e5f0',
  },
  placeHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  placeNumber: {
    fontSize: 16,
    fontWeight: '700',
    color: '#3498db',
    marginRight: 12,
    marginTop: 2,
  },
  placeInfo: {
    flex: 1,
  },
  placeName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2c3e50',
  },
  placeAddress: {
    fontSize: 14,
    color: '#7f8c8d',
    marginTop: 2,
  },
  placeDetails: {
    marginLeft: 28,
  },
  placeTime: {
    fontSize: 14,
    color: '#2c3e50',
    fontWeight: '600',
  },
  placeDuration: {
    fontSize: 14,
    color: '#7f8c8d',
    marginTop: 2,
  },
  placeRating: {
    fontSize: 14,
    color: '#f39c12',
    marginTop: 2,
  },
  bookingSection: {
    marginBottom: 24,
  },
  bookingSectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2c3e50',
    marginBottom: 12,
  },
  bookingItem: {
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
  },
  bookingTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2c3e50',
  },
  bookingDetails: {
    fontSize: 14,
    color: '#7f8c8d',
    marginTop: 2,
  },
  totalSection: {
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
  },
  totalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2c3e50',
    marginBottom: 12,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  totalLabel: {
    fontSize: 16,
    color: '#7f8c8d',
  },
  totalValue: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2c3e50',
  },
  totalDivider: {
    height: 1,
    backgroundColor: '#e1e5f0',
    marginVertical: 8,
  },
  totalGrandLabel: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2c3e50',
  },
  totalGrandValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2c3e50',
  },
  footer: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  footerText: {
    fontSize: 14,
    color: '#7f8c8d',
    fontStyle: 'italic',
  },
  actionButtons: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#e1e5f0',
  },
  printButton: {
    backgroundColor: '#3498db',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
  },
  printButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
});

export default PrintItinerary;